### PR TITLE
Update google-musicmanager.xml

### PR DESCRIPTION
**Pull request by Squidly271**

### CODE REVIEW

**Comment by Squidly271** [comment]
Hoping that removing the extraneous white space at the end of the file fixes the CA problem

**Comment by rix1337** [comment]
Thank you squid, as always.

Did not find this myself.

**Comment by Squidly271** [comment]
Well now I've got another problem.  Was trying to fix this originally by adjusting the URL for the repo, and now the feed has dropped you altogether, and even on reverting it back it won't pick you up.  Going to try and get LSIO to reboot the host and go from there.

**Comment by rix1337** [comment]
Oh, that sounds like a whole other issue..

Please let me know if I need to change anything.

**Pull request merged**
